services:
  indexer:
    build:
      context: .
      dockerfile: Dockerfile.indexer
    volumes:
      - .:/app/project_path
    working_dir: /app/project_path
    entrypoint: ["/app/rindexer"]
    command: ["start", "indexer"]
    environment:
      DATABASE_URL: rindexer.db
