services:
  api:
    image: ghcr.io/deluXtreme/subindexer:api-latest
    ports:
      - "${API_PORT:-3000}:8080"
    env_file:
      - .env
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:rindexer@postgresql:5432/postgres
      PORT: 8080
