services:
  indexer:
    image: ghcr.io/bh2smith/arak:main
    volumes:
      - .:/app/project_path
    working_dir: /app/project_path
    entrypoint: ["/usr/bin/tini", "--"]
    command: ["/opt/arak/arak"]
