volumes:
  postgres_data:
    driver: local

services:
  postgresql:
    image: postgres:latest
    shm_size: 1g
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5440:5432
    env_file:
      - ./.env
  indexer:
    image: ghcr.io/joshstevens19/rindexer
    depends_on:
      - postgresql
    volumes:
      - .:/app/project_path
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app/project_path
    command: ["start", "indexer"]
    environment:
      DATABASE_URL: postgres://postgres:rindexer@postgresql:5432/postgres
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "3000:8080"
    depends_on:
      - postgresql
    environment:
      DATABASE_URL: postgres://postgres:rindexer@postgresql:5432/postgres
      PORT: 8080
