name: Publish API Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*' # Optional: versioned tags like v1.0.0

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image tag
        id: vars
        run: |
          IMAGE_TAG=ghcr.io/${{ github.repository }}:api-latest
          echo "image_tag=${IMAGE_TAG,,}" >> $GITHUB_OUTPUT

      - name: Build and Push API Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.api
          push: true
          tags: ${{ steps.vars.outputs.image_tag }}
